# Generated by Django 5.2.16 on 2026-08-01 09:04

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('encounters', '0001_initial'),
        ('patients', '0003_patientallergy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TerminologySource',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('source_type', models.CharField(choices=[('ICD_11', 'WHO ICD-11'), ('ICD_10', 'WHO ICD-10'), ('CPT', 'CPT'), ('LOCAL', 'Local terminology'), ('OTHER', 'Other')], db_index=True, max_length=20)),
                ('organization', models.CharField(blank=True, max_length=150)),
                ('release_version', models.CharField(blank=True, db_index=True, help_text='Examples: 2026-01, ICD-10 2019, CPT 2026.', max_length=50)),
                ('canonical_url', models.URLField(blank=True, max_length=500)),
                ('api_base_url', models.URLField(blank=True, max_length=500)),
                ('language', models.CharField(db_index=True, default='en', max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('requires_license', models.BooleanField(default=False, help_text='True for terminology whose content requires a separate license, such as CPT.')),
                ('last_synchronized_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'terminology source',
                'verbose_name_plural': 'terminology sources',
                'ordering': ['source_type', 'name', '-release_version'],
            },
        ),
        migrations.CreateModel(
            name='ClinicalConcept',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, db_index=True, help_text='Classification code such as ICD-10 A00.0 or ICD-11 1A00.', max_length=40)),
                ('title', models.CharField(db_index=True, max_length=500)),
                ('fully_specified_name', models.CharField(blank=True, max_length=700)),
                ('short_description', models.TextField(blank=True)),
                ('definition', models.TextField(blank=True)),
                ('concept_kind', models.CharField(choices=[('DISEASE', 'Disease'), ('DISORDER', 'Disorder'), ('INJURY', 'Injury'), ('SIGN', 'Sign'), ('SYMPTOM', 'Symptom'), ('FINDING', 'Clinical finding'), ('EXTERNAL_CAUSE', 'External cause'), ('ENCOUNTER_REASON', 'Reason for encounter'), ('PROCEDURE', 'Procedure'), ('EXTENSION_CODE', 'Extension code'), ('OTHER', 'Other')], db_index=True, default='OTHER', max_length=30)),
                ('foundation_uri', models.URLField(blank=True, db_index=True, help_text='WHO ICD-11 Foundation entity URI.', max_length=700)),
                ('linearization_uri', models.URLField(blank=True, db_index=True, help_text='WHO ICD-11 MMS linearization URI.', max_length=700)),
                ('external_id', models.CharField(blank=True, db_index=True, help_text='Identifier supplied by the terminology provider.', max_length=255)),
                ('chapter_code', models.CharField(blank=True, db_index=True, max_length=40)),
                ('chapter_title', models.CharField(blank=True, max_length=300)),
                ('browser_url', models.URLField(blank=True, max_length=700)),
                ('is_leaf', models.BooleanField(db_index=True, default=False, help_text='Indicates whether the concept has no narrower children.')),
                ('is_billable', models.BooleanField(db_index=True, default=False, help_text='Indicates that the source considers this code usable at the lowest reportable level. This does not establish local billing.')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('imported_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('source_payload', models.JSONField(blank=True, default=dict, help_text='Selected original API data retained for synchronization and troubleshooting.')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='diagnoses.clinicalconcept')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='concepts', to='diagnoses.terminologysource')),
            ],
            options={
                'verbose_name': 'clinical concept',
                'verbose_name_plural': 'clinical concepts',
                'ordering': ['code', 'title'],
            },
        ),
        migrations.CreateModel(
            name='PatientDiagnosis',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('diagnosis_type', models.CharField(choices=[('PRINCIPAL', 'Principal diagnosis'), ('PRIMARY', 'Primary diagnosis'), ('SECONDARY', 'Secondary diagnosis'), ('COMORBIDITY', 'Comorbidity'), ('COMPLICATION', 'Complication'), ('DIFFERENTIAL', 'Differential diagnosis'), ('ADMISSION', 'Admission diagnosis'), ('DISCHARGE', 'Discharge diagnosis'), ('CHRONIC_PROBLEM', 'Chronic problem'), ('OTHER', 'Other')], db_index=True, default='PRIMARY', max_length=30)),
                ('clinical_status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('RESOLVED', 'Resolved'), ('IN_REMISSION', 'In remission'), ('RECURRENCE', 'Recurrence'), ('ENTERED_IN_ERROR', 'Entered in error')], db_index=True, default='ACTIVE', max_length=30)),
                ('verification_status', models.CharField(choices=[('PROVISIONAL', 'Provisional'), ('DIFFERENTIAL', 'Differential'), ('CONFIRMED', 'Confirmed'), ('REFUTED', 'Refuted'), ('UNCONFIRMED', 'Unconfirmed')], db_index=True, default='CONFIRMED', max_length=30)),
                ('severity', models.CharField(choices=[('MILD', 'Mild'), ('MODERATE', 'Moderate'), ('SEVERE', 'Severe'), ('CRITICAL', 'Critical'), ('UNSPECIFIED', 'Unspecified')], db_index=True, default='UNSPECIFIED', max_length=20)),
                ('diagnosed_on', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('onset_date', models.DateField(blank=True, db_index=True, null=True)),
                ('resolved_on', models.DateField(blank=True, db_index=True, null=True)),
                ('code_snapshot', models.CharField(blank=True, max_length=40)),
                ('display_snapshot', models.CharField(max_length=500)),
                ('source_snapshot', models.CharField(blank=True, max_length=150)),
                ('notes', models.TextField(blank=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('is_current_problem', models.BooleanField(db_index=True, default=True)),
                ('is_sensitive', models.BooleanField(db_index=True, default=False)),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patient_diagnoses', to='diagnoses.clinicalconcept')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_patient_diagnoses', to=settings.AUTH_USER_MODEL)),
                ('encounter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnoses', to='encounters.encounter')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diagnoses', to='patients.patient')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorded_patient_diagnoses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'patient diagnosis',
                'verbose_name_plural': 'patient diagnoses',
                'ordering': ['-diagnosed_on', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PatientDiagnosisManifestation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('manifestation_type', models.CharField(choices=[('SYMPTOM', 'Symptom'), ('SIGN', 'Sign'), ('FINDING', 'Clinical finding')], db_index=True, default='SYMPTOM', max_length=20)),
                ('description', models.CharField(blank=True, help_text='Patient-specific description or wording.', max_length=500)),
                ('onset_date', models.DateField(blank=True, null=True)),
                ('resolved_on', models.DateField(blank=True, null=True)),
                ('severity', models.CharField(choices=[('MILD', 'Mild'), ('MODERATE', 'Moderate'), ('SEVERE', 'Severe'), ('CRITICAL', 'Critical'), ('UNSPECIFIED', 'Unspecified')], default='UNSPECIFIED', max_length=20)),
                ('is_present', models.BooleanField(db_index=True, default=True, help_text='False can represent a pertinent negative.')),
                ('notes', models.TextField(blank=True)),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patient_manifestations', to='diagnoses.clinicalconcept')),
                ('diagnosis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manifestations', to='diagnoses.patientdiagnosis')),
            ],
            options={
                'ordering': ['manifestation_type', 'concept__title'],
            },
        ),
        migrations.CreateModel(
            name='ProcedureCode',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code_system', models.CharField(choices=[('CPT', 'CPT'), ('ICHI', 'WHO ICHI'), ('LOCAL', 'Local procedure code'), ('OTHER', 'Other')], db_index=True, max_length=20)),
                ('code', models.CharField(db_index=True, max_length=30)),
                ('title', models.CharField(db_index=True, max_length=500)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, db_index=True, max_length=150)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('source_payload', models.JSONField(blank=True, default=dict)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='procedure_codes', to='diagnoses.terminologysource')),
            ],
            options={
                'ordering': ['code_system', 'code'],
            },
        ),
        migrations.CreateModel(
            name='ClinicalConceptRelationship',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('relationship_type', models.CharField(choices=[('MAPS_TO', 'Maps to'), ('EQUIVALENT_TO', 'Equivalent to'), ('BROADER_THAN', 'Broader than'), ('NARROWER_THAN', 'Narrower than'), ('ASSOCIATED_SYMPTOM', 'Associated symptom'), ('ASSOCIATED_SIGN', 'Associated sign'), ('DIFFERENTIAL', 'Differential diagnosis'), ('EXCLUDES', 'Excludes'), ('CAUSED_BY', 'Caused by'), ('COMPLICATION_OF', 'Complication of'), ('OTHER', 'Other')], db_index=True, max_length=40)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('mapping_equivalence', models.CharField(blank=True, help_text='Optional mapping quality such as exact, broader, narrower, or approximate.', max_length=50)),
                ('confidence_score', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('source_concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relationships', to='diagnoses.clinicalconcept')),
                ('target_concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relationships', to='diagnoses.clinicalconcept')),
            ],
            options={
                'ordering': ['source_concept', 'relationship_type', 'target_concept'],
                'constraints': [models.UniqueConstraint(fields=('source_concept', 'target_concept', 'relationship_type'), name='unique_clinical_concept_relationship'), models.CheckConstraint(condition=models.Q(('source_concept', models.F('target_concept')), _negated=True), name='prevent_self_concept_relationship'), models.CheckConstraint(condition=models.Q(('confidence_score__isnull', True), models.Q(('confidence_score__gte', 0), ('confidence_score__lte', 1)), _connector='OR'), name='concept_relationship_confidence_range')],
            },
        ),
        migrations.CreateModel(
            name='ClinicalConceptTerm',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('term', models.CharField(db_index=True, max_length=500)),
                ('term_type', models.CharField(choices=[('SYNONYM', 'Synonym'), ('INCLUSION', 'Inclusion term'), ('ABBREVIATION', 'Abbreviation'), ('COMMON_NAME', 'Common name'), ('LOCAL_TERM', 'Local term'), ('SEARCH_TERM', 'Search term'), ('OTHER', 'Other')], db_index=True, default='SYNONYM', max_length=30)),
                ('language', models.CharField(db_index=True, default='en', max_length=20)),
                ('is_preferred', models.BooleanField(db_index=True, default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('source_payload', models.JSONField(blank=True, default=dict)),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='diagnoses.clinicalconcept')),
            ],
            options={
                'verbose_name': 'clinical concept term',
                'verbose_name_plural': 'clinical concept terms',
                'ordering': ['term'],
                'indexes': [models.Index(fields=['term', 'language', 'is_active'], name='dx_term_language_active_idx')],
                'constraints': [models.UniqueConstraint(fields=('concept', 'term', 'language'), name='unique_concept_term_language')],
            },
        ),
        migrations.AddIndex(
            model_name='patientdiagnosis',
            index=models.Index(fields=['patient', 'clinical_status'], name='dx_patient_status_idx'),
        ),
        migrations.AddIndex(
            model_name='patientdiagnosis',
            index=models.Index(fields=['patient', 'is_current_problem'], name='dx_patient_current_idx'),
        ),
        migrations.AddIndex(
            model_name='patientdiagnosis',
            index=models.Index(fields=['encounter', 'diagnosis_type'], name='dx_encounter_type_idx'),
        ),
        migrations.AddIndex(
            model_name='patientdiagnosis',
            index=models.Index(fields=['concept', 'diagnosed_on'], name='dx_concept_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='patientdiagnosis',
            constraint=models.CheckConstraint(condition=models.Q(('resolved_on__isnull', True), ('resolved_on__gte', models.F('diagnosed_on')), _connector='OR'), name='diagnosis_resolved_after_diagnosed'),
        ),
        migrations.AddConstraint(
            model_name='patientdiagnosis',
            constraint=models.CheckConstraint(condition=models.Q(('onset_date__isnull', True), ('onset_date__lte', models.F('diagnosed_on')), _connector='OR'), name='diagnosis_onset_before_diagnosed'),
        ),
        migrations.AddConstraint(
            model_name='patientdiagnosismanifestation',
            constraint=models.UniqueConstraint(fields=('diagnosis', 'concept'), name='unique_manifestation_per_diagnosis'),
        ),
        migrations.AddConstraint(
            model_name='patientdiagnosismanifestation',
            constraint=models.CheckConstraint(condition=models.Q(('resolved_on__isnull', True), ('onset_date__isnull', True), ('resolved_on__gte', models.F('onset_date')), _connector='OR'), name='manifestation_resolution_after_onset'),
        ),
        migrations.AddConstraint(
            model_name='procedurecode',
            constraint=models.UniqueConstraint(fields=('source', 'code'), name='unique_procedure_source_code'),
        ),
        migrations.AddIndex(
            model_name='clinicalconcept',
            index=models.Index(fields=['source', 'concept_kind', 'is_active'], name='dx_concept_source_kind_idx'),
        ),
        migrations.AddIndex(
            model_name='clinicalconcept',
            index=models.Index(fields=['source', 'chapter_code'], name='dx_concept_source_chapter_idx'),
        ),
        migrations.AddIndex(
            model_name='clinicalconcept',
            index=models.Index(fields=['title', 'is_active'], name='dx_concept_title_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='clinicalconcept',
            constraint=models.UniqueConstraint(condition=models.Q(('code', ''), _negated=True), fields=('source', 'code'), name='unique_clinical_concept_source_code'),
        ),
        migrations.AddConstraint(
            model_name='clinicalconcept',
            constraint=models.UniqueConstraint(condition=models.Q(('foundation_uri', ''), _negated=True), fields=('source', 'foundation_uri'), name='unique_concept_source_foundation_uri'),
        ),
        migrations.AddConstraint(
            model_name='clinicalconcept',
            constraint=models.UniqueConstraint(condition=models.Q(('linearization_uri', ''), _negated=True), fields=('source', 'linearization_uri'), name='unique_concept_source_linearization_uri'),
        ),
    ]
