# Generated by Django 5.2.16 on 2026-07-26 05:09

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('short_name', models.CharField(blank=True, max_length=100)),
                ('code', models.CharField(db_index=True, help_text='Unique facility code, such as JFK-MC, ELWA-HOSP, or MARGIBI-CLINIC-01.', max_length=30, unique=True)),
                ('facility_type', models.CharField(choices=[('national_hospital', 'National Referral Hospital'), ('regional_hospital', 'Regional Hospital'), ('county_hospital', 'County Hospital'), ('district_hospital', 'District Hospital'), ('private_hospital', 'Private Hospital'), ('clinic', 'Clinic'), ('health_center', 'Health Center'), ('health_post', 'Health Post'), ('maternity_center', 'Maternity Center'), ('laboratory', 'Laboratory'), ('pharmacy', 'Pharmacy'), ('imaging_center', 'Imaging Center'), ('rehabilitation_center', 'Rehabilitation Center'), ('mobile_clinic', 'Mobile Clinic'), ('community_program', 'Community Health Program'), ('other', 'Other')], db_index=True, default='clinic', max_length=40)),
                ('ownership_type', models.CharField(choices=[('government', 'Government'), ('private', 'Private'), ('faith_based', 'Faith-Based'), ('ngo', 'Non-Governmental Organization'), ('community', 'Community-Owned'), ('public_private', 'Public-Private Partnership'), ('other', 'Other')], db_index=True, default='government', max_length=30)),
                ('operational_status', models.CharField(choices=[('active', 'Active'), ('temporarily_closed', 'Temporarily Closed'), ('permanently_closed', 'Permanently Closed'), ('under_construction', 'Under Construction'), ('suspended', 'Suspended')], db_index=True, default='active', max_length=30)),
                ('ministry_license_number', models.CharField(blank=True, max_length=100)),
                ('accreditation_number', models.CharField(blank=True, max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=30, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number using digits and optional spaces, parentheses, hyphens, or a leading +.', regex='^\\+?[0-9()\\-\\s]{7,25}$')])),
                ('alternate_phone', models.CharField(blank=True, max_length=30, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number using digits and optional spaces, parentheses, hyphens, or a leading +.', regex='^\\+?[0-9()\\-\\s]{7,25}$')])),
                ('emergency_phone', models.CharField(blank=True, max_length=30, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number using digits and optional spaces, parentheses, hyphens, or a leading +.', regex='^\\+?[0-9()\\-\\s]{7,25}$')])),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('address_line_1', models.CharField(blank=True, max_length=200)),
                ('address_line_2', models.CharField(blank=True, max_length=200)),
                ('community_or_city', models.CharField(blank=True, db_index=True, max_length=150)),
                ('district', models.CharField(blank=True, db_index=True, max_length=150)),
                ('county_or_state', models.CharField(blank=True, db_index=True, max_length=150)),
                ('postal_code', models.CharField(blank=True, max_length=30)),
                ('country', models.CharField(default='Liberia', max_length=100)),
                ('directions_or_landmark', models.TextField(blank=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('bed_capacity', models.PositiveIntegerField(default=0, help_text='Configured inpatient-bed capacity.')),
                ('provides_emergency_services', models.BooleanField(default=False)),
                ('provides_inpatient_services', models.BooleanField(default=False)),
                ('provides_outpatient_services', models.BooleanField(default=True)),
                ('provides_maternity_services', models.BooleanField(default=False)),
                ('provides_surgical_services', models.BooleanField(default=False)),
                ('provides_laboratory_services', models.BooleanField(default=False)),
                ('provides_pharmacy_services', models.BooleanField(default=False)),
                ('provides_imaging_services', models.BooleanField(default=False)),
                ('timezone_name', models.CharField(default='Africa/Monrovia', max_length=100)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('parent_facility', models.ForeignKey(blank=True, help_text='Optional parent organization for satellite clinics or service locations.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='child_facilities', to='facilities.facility')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'facility',
                'verbose_name_plural': 'facilities',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=150)),
                ('code', models.CharField(max_length=30)),
                ('department_type', models.CharField(choices=[('clinical', 'Clinical'), ('nursing', 'Nursing'), ('diagnostic', 'Diagnostic'), ('pharmacy', 'Pharmacy'), ('administrative', 'Administrative'), ('finance', 'Finance'), ('support', 'Support Service'), ('other', 'Other')], db_index=True, default='clinical', max_length=30)),
                ('description', models.TextField(blank=True)),
                ('phone_extension', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_clinical', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departments', to='facilities.facility')),
            ],
            options={
                'ordering': ('facility__name', 'name'),
            },
        ),
        migrations.CreateModel(
            name='ClinicalUnit',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=150)),
                ('code', models.CharField(max_length=30)),
                ('unit_type', models.CharField(choices=[('emergency', 'Emergency'), ('outpatient', 'Outpatient'), ('inpatient', 'Inpatient'), ('intensive_care', 'Intensive Care'), ('operating_room', 'Operating Room'), ('recovery', 'Post-Anesthesia Recovery'), ('maternity', 'Maternity'), ('laboratory', 'Laboratory'), ('pharmacy', 'Pharmacy'), ('radiology', 'Radiology'), ('rehabilitation', 'Rehabilitation'), ('community', 'Community Health'), ('other', 'Other')], db_index=True, default='outpatient', max_length=30)),
                ('description', models.TextField(blank=True)),
                ('floor_or_location', models.CharField(blank=True, max_length=100)),
                ('accepts_admissions', models.BooleanField(default=False)),
                ('is_clinical', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clinical_units', to='facilities.department')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clinical_units', to='facilities.facility')),
            ],
            options={
                'ordering': ('facility__name', 'name'),
            },
        ),
        migrations.CreateModel(
            name='FacilityOperatingHour',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('weekday', models.PositiveSmallIntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')])),
                ('opens_at', models.TimeField(blank=True, null=True)),
                ('closes_at', models.TimeField(blank=True, null=True)),
                ('is_closed', models.BooleanField(default=False)),
                ('is_24_hours', models.BooleanField(default=False)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operating_hours', to='facilities.facility')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('facility', 'weekday'),
            },
        ),
        migrations.CreateModel(
            name='FacilityService',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=30)),
                ('category', models.CharField(choices=[('general_medicine', 'General Medicine'), ('emergency', 'Emergency Care'), ('surgery', 'Surgery'), ('maternity', 'Maternity'), ('pediatrics', 'Pediatrics'), ('mental_health', 'Mental Health'), ('laboratory', 'Laboratory'), ('pharmacy', 'Pharmacy'), ('imaging', 'Imaging'), ('rehabilitation', 'Rehabilitation'), ('dental', 'Dental'), ('hiv_tb', 'HIV/TB Services'), ('vaccination', 'Vaccination'), ('community_health', 'Community Health'), ('other', 'Other')], db_index=True, default='general_medicine', max_length=40)),
                ('description', models.TextField(blank=True)),
                ('requires_appointment', models.BooleanField(default=False)),
                ('accepts_walk_ins', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='facilities.facility')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('facility__name', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=30)),
                ('room_type', models.CharField(choices=[('examination', 'Examination Room'), ('patient_room', 'Patient Room'), ('operating_room', 'Operating Room'), ('procedure_room', 'Procedure Room'), ('labor_room', 'Labor Room'), ('delivery_room', 'Delivery Room'), ('recovery_room', 'Recovery Room'), ('isolation_room', 'Isolation Room'), ('consultation', 'Consultation Room'), ('laboratory', 'Laboratory Room'), ('storage', 'Storage Room'), ('other', 'Other')], db_index=True, default='patient_room', max_length=30)),
                ('floor', models.CharField(blank=True, max_length=50)),
                ('capacity', models.PositiveSmallIntegerField(default=1)),
                ('is_negative_pressure', models.BooleanField(default=False)),
                ('is_isolation_capable', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('clinical_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rooms', to='facilities.clinicalunit')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rooms', to='facilities.facility')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('facility__name', 'clinical_unit__name', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=30)),
                ('bed_type', models.CharField(choices=[('standard', 'Standard'), ('icu', 'Intensive Care'), ('pediatric', 'Pediatric'), ('maternity', 'Maternity'), ('neonatal', 'Neonatal'), ('emergency', 'Emergency'), ('recovery', 'Recovery'), ('isolation', 'Isolation'), ('observation', 'Observation'), ('other', 'Other')], db_index=True, default='standard', max_length=30)),
                ('status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('reserved', 'Reserved'), ('cleaning', 'Cleaning'), ('maintenance', 'Maintenance'), ('out_of_service', 'Out of Service')], db_index=True, default='available', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('clinical_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='beds', to='facilities.clinicalunit')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='beds', to='facilities.facility')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='beds', to='facilities.room')),
            ],
            options={
                'ordering': ('facility__name', 'clinical_unit__name', 'code'),
            },
        ),
        migrations.AddIndex(
            model_name='facility',
            index=models.Index(fields=['name', 'is_active'], name='facility_name_active_idx'),
        ),
        migrations.AddIndex(
            model_name='facility',
            index=models.Index(fields=['county_or_state', 'district'], name='facility_location_idx'),
        ),
        migrations.AddIndex(
            model_name='facility',
            index=models.Index(fields=['facility_type', 'operational_status'], name='facility_type_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='facility',
            constraint=models.CheckConstraint(condition=models.Q(('latitude__isnull', True), models.Q(('latitude__gte', -90), ('latitude__lte', 90)), _connector='OR'), name='facility_latitude_valid'),
        ),
        migrations.AddConstraint(
            model_name='facility',
            constraint=models.CheckConstraint(condition=models.Q(('longitude__isnull', True), models.Q(('longitude__gte', -180), ('longitude__lte', 180)), _connector='OR'), name='facility_longitude_valid'),
        ),
        migrations.AddConstraint(
            model_name='facility',
            constraint=models.CheckConstraint(condition=models.Q(('id', models.F('parent_facility')), _negated=True), name='facility_not_own_parent'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['facility', 'is_active'], name='department_facility_active_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['department_type', 'is_active'], name='department_type_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(fields=('facility', 'code'), name='department_facility_code_unique'),
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(fields=('facility', 'name'), name='department_facility_name_unique'),
        ),
        migrations.AddIndex(
            model_name='clinicalunit',
            index=models.Index(fields=['facility', 'unit_type', 'is_active'], name='clinical_unit_lookup_idx'),
        ),
        migrations.AddConstraint(
            model_name='clinicalunit',
            constraint=models.UniqueConstraint(fields=('facility', 'code'), name='clinical_unit_facility_code_unique'),
        ),
        migrations.AddConstraint(
            model_name='clinicalunit',
            constraint=models.UniqueConstraint(fields=('facility', 'name'), name='clinical_unit_facility_name_unique'),
        ),
        migrations.AddConstraint(
            model_name='facilityoperatinghour',
            constraint=models.UniqueConstraint(fields=('facility', 'weekday'), name='facility_weekday_hours_unique'),
        ),
        migrations.AddConstraint(
            model_name='facilityservice',
            constraint=models.UniqueConstraint(fields=('facility', 'code'), name='facility_service_code_unique'),
        ),
        migrations.AddConstraint(
            model_name='facilityservice',
            constraint=models.UniqueConstraint(fields=('facility', 'name'), name='facility_service_name_unique'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['clinical_unit', 'is_active'], name='room_unit_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.UniqueConstraint(fields=('facility', 'code'), name='room_facility_code_unique'),
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.CheckConstraint(condition=models.Q(('capacity__gte', 1)), name='room_capacity_positive'),
        ),
        migrations.AddIndex(
            model_name='bed',
            index=models.Index(fields=['clinical_unit', 'status', 'is_active'], name='bed_unit_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='bed',
            constraint=models.UniqueConstraint(fields=('facility', 'code'), name='bed_facility_code_unique'),
        ),
    ]
