# Generated by Django 5.2.16 on 2026-07-27 02:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facilities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('system_admin', 'System Administrator'), ('facility_admin', 'Facility Administrator'), ('physician', 'Physician'), ('nurse', 'Nurse'), ('nurse_practitioner', 'Nurse Practitioner'), ('pharmacist', 'Pharmacist'), ('lab_technician', 'Laboratory Technician'), ('radiology_technician', 'Radiology Technician'), ('data_analyst', 'Healthcare Data Analyst'), ('informaticist', 'Nursing Informaticist'), ('billing_officer', 'Billing Officer'), ('receptionist', 'Receptionist'), ('community_health_worker', 'Community Health Worker'), ('auditor', 'Auditor'), ('patient', 'Patient')], db_index=True, default='nurse', max_length=40)),
                ('employee_id', models.CharField(blank=True, db_index=True, max_length=50)),
                ('professional_license_number', models.CharField(blank=True, max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=30)),
                ('job_title', models.CharField(blank=True, max_length=150)),
                ('department', models.CharField(blank=True, max_length=150)),
                ('must_change_password', models.BooleanField(default=False, help_text='Require the user to change their password after login.')),
                ('is_clinical_staff', models.BooleanField(default=False, help_text='Identifies users who provide direct clinical care.')),
                ('is_active_staff', models.BooleanField(default=True, help_text='Controls whether the staff profile is active.')),
                ('last_activity', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_profiles', to='facilities.facility')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'ordering': ['user__last_name', 'user__first_name'],
                'indexes': [models.Index(fields=['role', 'is_active_staff'], name='accounts_us_role_1dccf2_idx'), models.Index(fields=['facility', 'role'], name='accounts_us_facilit_7b41d4_idx')],
            },
        ),
    ]
