# Generated by Django 5.2.16 on 2026-08-08 01:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('encounters', '0003_encounter_cancelled_at_encounter_cancelled_by_and_more'),
        ('patients', '0003_patientallergy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('note_type', models.CharField(choices=[('progress', 'Progress Note'), ('soap', 'SOAP Note'), ('physician', 'Physician Note'), ('np', 'Nurse Practitioner Note'), ('nursing', 'Nursing Note'), ('admission', 'Admission Note'), ('consultation', 'Consultation Note'), ('procedure', 'Procedure Note'), ('discharge', 'Discharge Note'), ('case_management', 'Case Management Note'), ('care_coordination', 'Care Coordination Note'), ('telephone', 'Telephone Note'), ('follow_up', 'Follow-up Note'), ('general', 'General Clinical Note')], db_index=True, default='progress', max_length=30)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('signed', 'Signed'), ('amended', 'Amended'), ('voided', 'Voided')], db_index=True, default='draft', max_length=20)),
                ('title', models.CharField(blank=True, help_text='Optional descriptive note title.', max_length=200)),
                ('subjective', models.TextField(blank=True, help_text='Patient-reported symptoms, history, concerns, and other subjective information.')),
                ('objective', models.TextField(blank=True, help_text='Physical examination findings, observations, measurements, and objective clinical information.')),
                ('assessment', models.TextField(blank=True, help_text='Clinical impression, interpretation, differential considerations, and assessment.')),
                ('plan', models.TextField(blank=True, help_text='Treatment plan, investigations, referrals, education, follow-up, and other planned interventions.')),
                ('content', models.TextField(blank=True, help_text='Additional narrative documentation that does not fit within the structured SOAP sections.')),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('amended_at', models.DateTimeField(blank=True, null=True)),
                ('amendment_reason', models.TextField(blank=True)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('void_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amended_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clinical_notes_amended', to=settings.AUTH_USER_MODEL)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clinical_notes_authored', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clinical_notes_created', to=settings.AUTH_USER_MODEL)),
                ('encounter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clinical_notes', to='encounters.encounter')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clinical_notes', to='patients.patient')),
                ('signed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clinical_notes_signed', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clinical_notes_updated', to=settings.AUTH_USER_MODEL)),
                ('voided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clinical_notes_voided', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Clinical Note',
                'verbose_name_plural': 'Clinical Notes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['patient', '-created_at'], name='clin_note_patient_created_idx'), models.Index(fields=['encounter', '-created_at'], name='clin_note_enc_created_idx'), models.Index(fields=['patient', 'status'], name='clin_note_patient_status_idx'), models.Index(fields=['patient', 'note_type'], name='clin_note_patient_type_idx')],
            },
        ),
    ]
