# Generated by Django 5.2.16 on 2026-08-08 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicalnote',
            name='chief_complaint',
            field=models.CharField(db_index=True, default='None', help_text='Primary reason, symptom, concern, or clinical issue being documented in this note.', max_length=255),
            preserve_default=False,
        ),
    ]
