# Generated by Django 5.2.16 on 2026-08-01 09:04

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0003_patientallergy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Encounter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('encounter_number', models.CharField(blank=True, db_index=True, editable=False, help_text='Automatically generated encounter identifier.', max_length=30, unique=True)),
                ('encounter_type', models.CharField(choices=[('OUTPATIENT', 'Outpatient'), ('INPATIENT', 'Inpatient'), ('EMERGENCY', 'Emergency'), ('OBSERVATION', 'Observation'), ('TELEHEALTH', 'Telehealth'), ('HOME_VISIT', 'Home visit'), ('COMMUNITY', 'Community care'), ('MATERNITY', 'Maternity'), ('SURGICAL', 'Surgical'), ('PHARMACY', 'Pharmacy consultation'), ('LABORATORY', 'Laboratory only'), ('IMAGING', 'Imaging only'), ('OTHER', 'Other')], db_index=True, default='OUTPATIENT', max_length=30)),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('SCHEDULED', 'Scheduled'), ('ARRIVED', 'Arrived'), ('TRIAGED', 'Triaged'), ('IN_PROGRESS', 'In progress'), ('ON_HOLD', 'On hold'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('ENTERED_IN_ERROR', 'Entered in error')], db_index=True, default='PLANNED', max_length=30)),
                ('priority', models.CharField(choices=[('ROUTINE', 'Routine'), ('URGENT', 'Urgent'), ('EMERGENCY', 'Emergency')], db_index=True, default='ROUTINE', max_length=20)),
                ('reason_for_visit', models.CharField(blank=True, db_index=True, help_text='Chief complaint or primary reason for the encounter.', max_length=500)),
                ('start_datetime', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('end_datetime', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attending_provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attending_encounters', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_encounters', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='encounters', to='patients.patient')),
            ],
            options={
                'verbose_name': 'encounter',
                'verbose_name_plural': 'encounters',
                'ordering': ['-start_datetime', '-created_at'],
                'indexes': [models.Index(fields=['patient', 'status'], name='enc_patient_status_idx'), models.Index(fields=['patient', 'start_datetime'], name='enc_patient_start_idx'), models.Index(fields=['encounter_type', 'status'], name='enc_type_status_idx'), models.Index(fields=['attending_provider', 'status'], name='enc_provider_status_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_datetime__isnull', True), ('end_datetime__gte', models.F('start_datetime')), _connector='OR'), name='encounter_end_after_start')],
            },
        ),
    ]
