# Generated by Django 5.2.16 on 2026-08-02 04:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encounters', '0001_initial'),
        ('patients', '0003_patientallergy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='encounter',
            name='arrived_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Date and time the patient arrived or checked in.', null=True),
        ),
        migrations.AddField(
            model_name='encounter',
            name='check_in_user',
            field=models.ForeignKey(blank=True, help_text='Staff member who checked the patient in.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_in_encounters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='encounter',
            name='clinical_start_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Date and time direct clinical care began.', null=True),
        ),
        migrations.AddField(
            model_name='encounter',
            name='completed_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Date and time the encounter was clinically completed.', null=True),
        ),
        migrations.AddField(
            model_name='encounter',
            name='identity_verified',
            field=models.BooleanField(db_index=True, default=False, help_text='Indicates that staff verified the patient using the required patient identifiers.'),
        ),
        migrations.AddField(
            model_name='encounter',
            name='registered_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Date and time registration requirements were completed for this encounter.', null=True),
        ),
        migrations.AddField(
            model_name='encounter',
            name='registered_by',
            field=models.ForeignKey(blank=True, help_text='Staff member who completed encounter registration.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_encounters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='encounter',
            name='registration_completed',
            field=models.BooleanField(db_index=True, default=False, help_text='Indicates that the minimum required registration information has been completed for this visit.'),
        ),
        migrations.AddField(
            model_name='encounter',
            name='triaged_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Date and time triage was completed.', null=True),
        ),
        migrations.AddField(
            model_name='encounter',
            name='triaged_by',
            field=models.ForeignKey(blank=True, help_text='Nurse or clinician who completed triage.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triaged_encounters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='attending_provider',
            field=models.ForeignKey(blank=True, help_text='Primary provider responsible for this encounter.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attending_encounters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='created_by',
            field=models.ForeignKey(help_text='User who created the encounter record.', on_delete=django.db.models.deletion.PROTECT, related_name='created_encounters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='end_datetime',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Administrative end of the encounter. This normally matches completed_at when the encounter is completed.', null=True),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='patient',
            field=models.ForeignKey(help_text='The patient receiving care during this encounter.', on_delete=django.db.models.deletion.PROTECT, related_name='encounters', to='patients.patient'),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='start_datetime',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Planned or administrative beginning of the encounter. Use clinical_start_at for the time direct clinical care began.'),
        ),
        migrations.AddIndex(
            model_name='encounter',
            index=models.Index(fields=['status', 'arrived_at'], name='enc_status_arrived_idx'),
        ),
        migrations.AddIndex(
            model_name='encounter',
            index=models.Index(fields=['status', 'triaged_at'], name='enc_status_triaged_idx'),
        ),
        migrations.AddIndex(
            model_name='encounter',
            index=models.Index(fields=['registration_completed', 'identity_verified'], name='enc_registration_identity_idx'),
        ),
        migrations.AddConstraint(
            model_name='encounter',
            constraint=models.CheckConstraint(condition=models.Q(('completed_at__isnull', True), ('completed_at__gte', models.F('start_datetime')), _connector='OR'), name='enc_completed_after_start'),
        ),
        migrations.AddConstraint(
            model_name='encounter',
            constraint=models.CheckConstraint(condition=models.Q(('clinical_start_at__isnull', True), ('clinical_start_at__gte', models.F('start_datetime')), _connector='OR'), name='enc_clinical_start_after_start'),
        ),
    ]
