# Generated by Django 5.2.16 on 2026-08-02 11:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encounters', '0002_encounter_arrived_at_encounter_check_in_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='encounter',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='encounter',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_encounters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='encounter',
            name='clinical_started_by',
            field=models.ForeignKey(blank=True, editable=False, help_text='Automatically populated with the clinician who began direct clinical care.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinically_started_encounters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='encounter',
            name='completed_by',
            field=models.ForeignKey(blank=True, editable=False, help_text='Automatically populated with the staff member who completed the encounter.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_encounters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='encounter',
            name='entered_in_error_at',
            field=models.DateTimeField(blank=True, db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='encounter',
            name='entered_in_error_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='erroneous_encounters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='encounter',
            name='identity_verified_at',
            field=models.DateTimeField(blank=True, db_index=True, editable=False, help_text='Automatically recorded when patient identity is verified.', null=True),
        ),
        migrations.AddField(
            model_name='encounter',
            name='identity_verified_by',
            field=models.ForeignKey(blank=True, editable=False, help_text="Automatically populated with the staff member who verified the patient's identity.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='identity_verified_encounters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='encounter',
            name='status_reason',
            field=models.CharField(blank=True, help_text='Reason for cancellation, hold status, or entry-in-error.', max_length=500),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='arrived_at',
            field=models.DateTimeField(blank=True, db_index=True, editable=False, help_text='Automatically recorded when the encounter status becomes arrived or advances beyond arrival.', null=True),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='check_in_user',
            field=models.ForeignKey(blank=True, editable=False, help_text='Automatically populated with the staff member who checked the patient in.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_in_encounters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='clinical_start_at',
            field=models.DateTimeField(blank=True, db_index=True, editable=False, help_text='Automatically recorded when direct clinical care begins.', null=True),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='completed_at',
            field=models.DateTimeField(blank=True, db_index=True, editable=False, help_text='Automatically recorded when the encounter is completed.', null=True),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='created_by',
            field=models.ForeignKey(editable=False, help_text='Automatically populated with the authenticated user who created the encounter.', on_delete=django.db.models.deletion.PROTECT, related_name='created_encounters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='end_datetime',
            field=models.DateTimeField(blank=True, db_index=True, editable=False, help_text='Administrative end of the encounter. Automatically populated when the encounter is completed.', null=True),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, editable=False),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='registered_at',
            field=models.DateTimeField(blank=True, db_index=True, editable=False, help_text='Automatically recorded when registration is marked complete.', null=True),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='registered_by',
            field=models.ForeignKey(blank=True, editable=False, help_text='Automatically populated with the staff member who completed encounter registration.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_encounters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='start_datetime',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Administrative beginning of the encounter. Automatically defaults to the time the encounter is created.'),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='triaged_at',
            field=models.DateTimeField(blank=True, db_index=True, editable=False, help_text='Automatically recorded when triage is completed.', null=True),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='triaged_by',
            field=models.ForeignKey(blank=True, editable=False, help_text='Automatically populated with the nurse or clinician who completed triage.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triaged_encounters', to=settings.AUTH_USER_MODEL),
        ),
    ]
