# Generated by Django 5.2.16 on 2026-08-06 17:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facilities', '0001_initial'),
        ('patients', '0003_patientallergy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('appointment_number', models.CharField(blank=True, db_index=True, max_length=30, unique=True)),
                ('appointment_type', models.CharField(choices=[('new_patient', 'New Patient'), ('follow_up', 'Follow-up'), ('procedure', 'Procedure'), ('laboratory', 'Laboratory'), ('imaging', 'Imaging'), ('therapy', 'Therapy'), ('telehealth', 'Telehealth'), ('home_visit', 'Home Visit'), ('other', 'Other')], db_index=True, default='follow_up', max_length=30)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('scheduled', 'Scheduled'), ('confirmed', 'Confirmed'), ('checked_in', 'Checked In'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('no_show', 'No Show'), ('cancelled', 'Cancelled'), ('entered_in_error', 'Entered in Error')], db_index=True, default='scheduled', max_length=30)),
                ('priority', models.CharField(choices=[('routine', 'Routine'), ('urgent', 'Urgent'), ('emergency', 'Emergency')], db_index=True, default='routine', max_length=20)),
                ('start_datetime', models.DateTimeField(db_index=True)),
                ('end_datetime', models.DateTimeField(db_index=True)),
                ('reason_for_visit', models.TextField()),
                ('patient_instructions', models.TextField(blank=True)),
                ('internal_notes', models.TextField(blank=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinical_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='facilities.clinicalunit')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments_created', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='facilities.department')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='facilities.facility')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='patients.patient')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='scheduled_appointments', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='facilities.room')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['start_datetime', 'appointment_number'],
                'indexes': [models.Index(fields=['facility', 'start_datetime'], name='adm_appt_facility_start'), models.Index(fields=['provider', 'start_datetime'], name='adm_appt_provider_start'), models.Index(fields=['status', 'start_datetime'], name='adm_appt_status_start')],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_datetime__gt', models.F('start_datetime'))), name='adm_appt_end_after_start')],
            },
        ),
    ]
