# Generated by Django 5.2.16 on 2026-07-27 02:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('relationship_type', models.CharField(choices=[('parent', 'Parent'), ('child', 'Child'), ('spouse', 'Spouse'), ('sibling', 'Sibling'), ('guardian', 'Guardian'), ('dependent', 'Dependent'), ('other', 'Other')], max_length=20)),
                ('notes', models.CharField(blank=True, max_length=250)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_from', to='patients.patient')),
                ('related_patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_to', to='patients.patient')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('patient', 'related_patient', 'relationship_type'), name='patient_relationship_unique'), models.CheckConstraint(condition=models.Q(('patient', models.F('related_patient')), _negated=True), name='patient_relationship_not_self')],
            },
        ),
    ]
