# Generated by Django 5.2.16 on 2026-07-30 02:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patientrelationship'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientAllergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allergy_type', models.CharField(choices=[('medication', 'Medication'), ('food', 'Food'), ('environmental', 'Environmental'), ('biologic', 'Biologic'), ('other', 'Other')], db_index=True, default='other', max_length=30)),
                ('substance', models.CharField(db_index=True, max_length=200)),
                ('reaction', models.CharField(blank=True, max_length=250)),
                ('severity', models.CharField(choices=[('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe'), ('life_threatening', 'Life-threatening'), ('unknown', 'Unknown')], db_index=True, default='unknown', max_length=30)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('resolved', 'Resolved'), ('error', 'Entered in error')], db_index=True, default='active', max_length=20)),
                ('verification_status', models.CharField(choices=[('unconfirmed', 'Unconfirmed'), ('confirmed', 'Confirmed'), ('refuted', 'Refuted')], default='unconfirmed', max_length=20)),
                ('onset_date', models.DateField(blank=True, null=True)),
                ('recorded_date', models.DateField(default=django.utils.timezone.localdate)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allergies', to='patients.patient')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-severity', 'substance'),
                'indexes': [models.Index(fields=['patient', 'status'], name='patient_allergy_status_idx'), models.Index(fields=['patient', 'severity'], name='patient_allergy_severity_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('patient', 'substance', 'allergy_type'), name='patient_active_allergy_unique')],
            },
        ),
    ]
