# Generated by Django 5.2.16 on 2026-08-06 20:11

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('encounters', '0003_encounter_cancelled_at_encounter_cancelled_by_and_more'),
        ('patients', '0003_patientallergy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VitalObservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recorded_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('position', models.CharField(blank=True, choices=[('sitting', 'Sitting'), ('standing', 'Standing'), ('supine', 'Supine'), ('prone', 'Prone'), ('lateral', 'Lateral'), ('other', 'Other'), ('not_recorded', 'Not recorded')], default='not_recorded', max_length=20)),
                ('temperature_celsius', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(Decimal('25.0')), django.core.validators.MaxValueValidator(Decimal('45.0'))])),
                ('temperature_site', models.CharField(blank=True, choices=[('oral', 'Oral'), ('axillary', 'Axillary'), ('tympanic', 'Tympanic'), ('temporal', 'Temporal'), ('rectal', 'Rectal'), ('skin', 'Skin'), ('other', 'Other'), ('not_recorded', 'Not recorded')], default='not_recorded', max_length=20)),
                ('heart_rate', models.PositiveSmallIntegerField(blank=True, help_text='Heart rate in beats per minute.', null=True, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(300)])),
                ('respiratory_rate', models.PositiveSmallIntegerField(blank=True, help_text='Respiratory rate in breaths per minute.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('systolic_blood_pressure', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(300)])),
                ('diastolic_blood_pressure', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(200)])),
                ('oxygen_saturation', models.DecimalField(blank=True, decimal_places=1, help_text='Peripheral oxygen saturation percentage.', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.0')), django.core.validators.MaxValueValidator(Decimal('100.0'))])),
                ('oxygen_delivery_method', models.CharField(blank=True, choices=[('room_air', 'Room air'), ('nasal_cannula', 'Nasal cannula'), ('simple_mask', 'Simple face mask'), ('venturi_mask', 'Venturi mask'), ('non_rebreather', 'Non-rebreather mask'), ('high_flow', 'High-flow nasal cannula'), ('cpap', 'CPAP'), ('bipap', 'BiPAP'), ('mechanical_ventilation', 'Mechanical ventilation'), ('other', 'Other'), ('not_recorded', 'Not recorded')], default='room_air', max_length=30)),
                ('oxygen_flow_lpm', models.DecimalField(blank=True, decimal_places=1, help_text='Supplemental oxygen flow in liters per minute.', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.0')), django.core.validators.MaxValueValidator(Decimal('100.0'))])),
                ('pain_score', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('height_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('20.0')), django.core.validators.MaxValueValidator(Decimal('300.0'))])),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.20')), django.core.validators.MaxValueValidator(Decimal('1000.00'))])),
                ('blood_glucose_mg_dl', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('1.0')), django.core.validators.MaxValueValidator(Decimal('2000.0'))])),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('final', 'Final'), ('corrected', 'Corrected'), ('entered_in_error', 'Entered in error')], db_index=True, default='final', max_length=30)),
                ('correction_reason', models.TextField(blank=True)),
                ('entered_in_error_reason', models.TextField(blank=True)),
                ('entered_in_error_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('encounter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vital_observations', to='encounters.encounter')),
                ('entered_in_error_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vitals_entered_in_error', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vital_observations', to='patients.patient')),
                ('recorded_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='recorded_vital_observations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'vital observation',
                'verbose_name_plural': 'vital observations',
                'ordering': ('-recorded_at', '-created_at'),
                'indexes': [models.Index(fields=['patient', 'recorded_at'], name='vital_patient_date_idx'), models.Index(fields=['encounter', 'recorded_at'], name='vital_encounter_date_idx'), models.Index(fields=['status', 'recorded_at'], name='vital_status_date_idx'), models.Index(fields=['recorded_by', 'recorded_at'], name='vital_recorder_date_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('systolic_blood_pressure__isnull', True), ('diastolic_blood_pressure__isnull', True), ('systolic_blood_pressure__gt', models.F('diastolic_blood_pressure')), _connector='OR'), name='vital_systolic_gt_diastolic')],
            },
        ),
    ]
